version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: upwork
      POSTGRES_PASSWORD: upwork123
      POSTGRES_DB: taskreminderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped


  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
